Controllers/ConsejeriaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ConsejeriaEpics.Models;
using ConsejeriaEpics.Data;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;

namespace ConsejeriaEpics.Controllers
{
    public class ConsejeriaController : Controller
    {
        private readonly ILogger<ConsejeriaController> _logger;
        private readonly ApplicationDbContext _context;

        private List<Requerimiento> listRequerimientos= new List<Requerimiento>();

        private List<Requerimiento> listMostrar= new List<Requerimiento>();

        public ConsejeriaController(ILogger<ConsejeriaController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
            listRequerimientos=_context.Requerimientos.ToList();
        }

        public IActionResult Index()
        {
            var status=HttpContext.Session.GetString("State");
            if(status!=null){
                var user = JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("SessionUser"));
                var tipo = user.Tipo;
                if(tipo=="C"){
                    return View();
                }else{
                    HttpContext.Session.Clear();
                    return RedirectToAction("Index","Login");
                }

            }else{
                return RedirectToAction("Index","Login");
            }           
        }

        public IActionResult Pendiente()
        {
            HttpContext.Session.SetString("Tipo","PENDIENTE");
            return RedirectToAction("Consejero","Listado");
        }

        public IActionResult Procesado()
        {
            HttpContext.Session.SetString("Tipo","EN PROCESO");
            return RedirectToAction("Consejero","Listado");
        }

        public IActionResult Terminado()
        {
            HttpContext.Session.SetString("Tipo","TERMINADO");
            return RedirectToAction("Consejero","Listado");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Consejeria/Index.cshtml
@{
    ViewData["Title"] = "Consejero";
}

 <section id="hero2" class="d-flex justify-content-center align-items-center">
    <div class="container position-relative" data-aos="zoom-in" data-aos-delay="100">

      <h1>Bienvenido Consejero<br></h1>
      <h1>De Ingenieria de Computación y Sistemas</h1>
    </div>
  </section>
 
 <section id="services" class="services section-bg">
    <div class="container">

      <div class="section-title">
        <h2 data-aos="fade-in">Funcionalidades del Consejero</h2>
        <p data-aos="fade-in" style="color: black;" class="center">Elige una de las funciones de acuerdo a tu necesidad</p>
      </div>

      <div class="row">
        <div class="col-md-6 d-flex align-items-stretch" data-aos="fade-right">
          <div class="card">
            <div class="card-img">
              <img src="~/img/pendientes.png" alt="...">
            </div>
            <div class="card-body">
              <h5 class="card-title"><a asp-controller="Consejeria" asp-action="Pendiente" >Requerimientos Pendientes</a></h5>
              <p class="card-text center"> Visualiza todos los requerimientos que faltan ser atendidos</p>
            </div>
          </div>
        </div>
        <div class="col-md-6   d-flex align-items-stretch" data-aos="fade-left">
          <div class="card">
            <div class="card-img">
              <img src="~/img/proceso.png " alt="...">
            </div>
            <div class="card-body">
              <h5 class="card-title"><a asp-controller="Consejeria" asp-action="Procesado" >Requerimientos en proceso</a></h5>
              <p class="card-text center" >Visualiza todos los requerimientos que estan en proceso</p>
        
            </div>
          </div>
          </div>
    </div>

 <div class="row">
        <div class="col-md-6 d-flex align-items-stretch" data-aos="fade-right">
          <div class="card">
            <div class="card-img">
              <img src="~/img/terminados.png" alt="...">
            </div>
            <div class="card-body">
              <h5 class="card-title"><a asp-area="" asp-controller="Consejeria" asp-action="Terminado">Requerimientos Terminados</a></h5>
              <p class="card-text center" >Visualiza todos los requerimientos que ya estan finalizados</p>
            </div>
          </div>
        </div>

        <div class="col-md-6 d-flex align-items-stretch" data-aos="fade-left">
          <div class="card">
            <div class="card-img">
              <img src="~/img/reportes.png" alt="...">
            </div>
            <div class="card-body">
              <h5 class="card-title"><a asp-area="" asp-controller="Listado" asp-action="Reportes">Reportes</a></h5>
              <p class="card-text center" >Visualiza todos los requerimientos atendidos según su categoría</p>
            </div>
          </div>
        </div>
  </div>




  </section>