Controllers/FormularioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ConsejeriaEpics.Models;
using ConsejeriaEpics.Data;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using System.Dynamic;

namespace ConsejeriaEpics.Controllers
{
    public class FormularioController : Controller
    {
        private readonly ILogger<FormularioController> _logger;
        private readonly ApplicationDbContext _context;

        public FormularioController(ILogger<FormularioController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            var status=HttpContext.Session.GetString("State");
            if(status!=null){
                var user = JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("SessionUser"));
                var tipo = user.Tipo;
                var requerimiento = new List<Requerimiento>();
                requerimiento.Add(new Requerimiento());
                if(tipo=="E"){
                    dynamic modelo = new ExpandoObject();
                    modelo.Categorias = _context.Categorias.ToList();
                    modelo.Requerimiento = requerimiento;
                    return View(modelo);
                }else{
                    HttpContext.Session.Clear();
                    return RedirectToAction("Index","Login");
                }

            }else{
                return RedirectToAction("Index","Login");
            }   
        }

        public IActionResult Envio(Requerimiento req){
            var user = JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("SessionUser"));
            req.User_ID = user.ID;
            req.Estado = "PENDIENTE";
            req.Fecha_Inicio = DateTime.Now;
            if(ModelState.IsValid){
                _context.Requerimientos.Add(req);
                _context.SaveChanges();
                return RedirectToAction("Estudiante","Listado");

            }else{
                return RedirectToAction("Index");
            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Formulario/Index.cshtml
@model dynamic

@{
    ViewData["Title"] = "Formulario de Solicitud";
}
 
 <section id="hero" class="d-flex justify-content-center align-items-center">
    <div class="container position-relative" data-aos="zoom-in" data-aos-delay="100">

      <h1>Agregar Requerimiento<br></h1>
      <h1>Agrega tu requerimiento y completa el formulario de acuerdo a tu problema</h1>
    </div>
  </section>
 

<section class="contact-box" style="background-color: white" >
    <div class="row no-gutters bg-dark">
        <div class="col-xl-5 col-lg-12 register-Solicitud">
        </div>
        <div class="col-xl-7 col-lg-12 d-flex">
             <div class="container align-self-center p-6" >
                 <h1 class="font-weight-bold mb-3" style="color: black;">Completa el formulario de Solicitud</h1>
                 <br>
                @foreach (Requerimiento req in @Model.Requerimiento){
                 <form asp-action="Envio" asp-controller="Formulario" method="POST">
                     <div class="form-group mb-3">
                        <label  class="font-weight-bold" style="color: black;">Tipo de Requerimiento:<span class="text-danger">*</span></label>
                        <br>
                        <select asp-for="@req.Tipo_Req" class="form-control" style="height: 70px; background-color: #910222; color:white;" >
                          @foreach (Categoria categoria in @Model.Categorias)
                          {
                              <option value="@categoria.ID">@categoria.Nombre</option>
                          }
                        </select>
                         <span class="text-danger"></span>
                     </div>
                     <br>
                     <div class="form-group mb-3">
                         <label  class="font-weight-bold" style="color: black;">Descripción del Problema:<span class="text-danger">*</span></label>
                         <textarea type="text"  style="background-color: #910222; color:white;" class="form-control" asp-for="@req.Detalle"></textarea>
                          <span  class="text-danger"></span>
                     </div>

                   <br>
                   <div style="text-align: center;">
                      <button class="get-started-btn scrollto" style="border-radius: 50px;margin:20px" type="submit">Regístrar</button>
                   </div>
             
                 </form>
                }
             </div>
        </div>
    </div>
</section>