Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ConsejeriaEpics.Models;
using ConsejeriaEpics.Data;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;

namespace ConsejeriaEpics.Controllers
{
    public class EstudianteController : Controller
    {
        private readonly ILogger<EstudianteController> _logger;
        private readonly ApplicationDbContext _context;

        public EstudianteController(ILogger<EstudianteController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            var status=HttpContext.Session.GetString("State");          
            if(status!=null){
                var user = JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("SessionUser"));
                var tipo = user.Tipo;
                if(tipo=="E"){
                    return View();
                }else{
                    HttpContext.Session.Clear();
                    return RedirectToAction("Index","Login");
                }

            }else{
                return RedirectToAction("Index","Login");
            }    
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ListadoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ConsejeriaEpics.Models;
using ConsejeriaEpics.Data;
using Newtonsoft.Json;
using System.Dynamic;
using Microsoft.AspNetCore.Http;

namespace ConsejeriaEpics.Controllers
{
    public class ListadoController : Controller
    {
        private readonly ILogger<ListadoController> _logger;
        private readonly ApplicationDbContext _context;

        private List<Requerimiento> listRequerimientos= new List<Requerimiento>();

        private List<Requerimiento> listMostrar= new List<Requerimiento>();

        private List<Categoria> listCategoria = new List<Categoria>();

        public ListadoController(ILogger<ListadoController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
            listRequerimientos=_context.Requerimientos.ToList();
            listCategoria=_context.Categorias.ToList();
        }


        public IActionResult Consejero()
        {
            var status=HttpContext.Session.GetString("State"); 
            if(status!=null){
                var user = JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("SessionUser"));
                var tipo = user.Tipo;
                if(tipo=="C"){
                    switch(HttpContext.Session.GetString("Tipo")){
                        case "PENDIENTE": Pendiente();
                                            break;
                        case "EN PROCESO": Procesado();
                                            break;
                        case "TERMINADO": Terminado();
                                            break;
                    }
                    return View();
                }else{
                    HttpContext.Session.Clear();
                    return RedirectToAction("Index","Login");
                }
            }else{
                return RedirectToAction("Index","Login");
            }    
        }

        public IActionResult Estudiante()
        {
            var status=HttpContext.Session.GetString("State");
            if(status!=null){
                var user = JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("SessionUser"));
                var tipo = user.Tipo;
                if(tipo=="E"){
                    dynamic modelo= new ExpandoObject();
                    foreach(Requerimiento req in listRequerimientos){
                        if(req.User_ID==user.ID){
                            listMostrar.Add(req);
                        }
                    }
                    modelo.Categorias=listCategoria;
                    modelo.Mostrar=listMostrar;
                    return View("Estudiante",modelo);
                }else{
                    HttpContext.Session.Clear();
                    return RedirectToAction("Index","Login");
                }
            }else{
                return RedirectToAction("Index","Login");
            }    
        }

        public IActionResult Reportes(){
            var user = JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("SessionUser"));
            var tipo = user.Tipo;
                if(tipo=="C"){
                    dynamic modelo = new ExpandoObject();
                    var listMostrar= new List<Requerimiento>();
                    modelo.Categorias=listCategoria;
                    modelo.Selected=1;
                    for(int i=0; i<listRequerimientos.Count; i++){
                        if(listRequerimientos[i].Tipo_Req==modelo.Selected){
                            listMostrar.Add(listRequerimientos[i]);
                        }
                    }
                    modelo.Mostrar=listMostrar;
                    return View("Reportes",modelo);
                }else{
                    HttpContext.Session.Clear();
                    return RedirectToAction("Index","Login");
                }

        }


        public IActionResult Pendiente()
        {
            foreach(Requerimiento req in listRequerimientos){
                if(req.Estado=="PENDIENTE"){
                    listMostrar.Add(req);
                }
            }
            dynamic modelo= new ExpandoObject();
            modelo.Titulo="Requerimientos Pendientes";
            modelo.Desc="Visualiza todos los requerimientos que aun no han sido atendidos";
            modelo.Mostrar=listMostrar;
            modelo.Categorias=listCategoria;
            modelo.ReqUser=null;
            return View("Consejero",modelo);
        }

        public IActionResult Procesado()
        {
            List<Requerimiento> listReqUser= new List<Requerimiento>();
            foreach(Requerimiento req in listRequerimientos){
                if(req.Estado=="EN PROCESO"){
                    if(req.Consejero_ID==(JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("SessionUser"))).ID){
                        listReqUser.Add(req);
                    }else{
                        listMostrar.Add(req);
                    }
                    
                }
            }
            dynamic modelo= new ExpandoObject();
            modelo.Titulo="Requerimientos En Proceso";
            modelo.Desc="Visualiza todos los requerimientos que estan siendo atendidos";
            modelo.ReqUser=listReqUser;
            modelo.Categorias=listCategoria;
            modelo.Mostrar=listMostrar;
            return View("Consejero",modelo);
        }

        public IActionResult Terminado()
        {
            foreach(Requerimiento req in listRequerimientos){
                if(req.Estado=="TERMINADO"){
                    listMostrar.Add(req);
                }
            }
            dynamic modelo= new ExpandoObject();
            modelo.Titulo="Requerimientos Terminados";
            modelo.Desc="Visualiza todos los requerimientos que ya han sido atendidos";
            modelo.Mostrar=listMostrar;
            modelo.Categorias=listCategoria;
            modelo.ReqUser=null;
            return View("Consejero",modelo);
        }


        public IActionResult Seleccionar(Requerimiento req){

            var user = JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("SessionUser"));
            Requerimiento requerimiento= _context.Requerimientos.Where(r => r.ID == req.ID).FirstOrDefault();
            _context.Remove(requerimiento);
            _context.SaveChanges();
            requerimiento.Consejero_ID= user.ID;  
            requerimiento.Estado= "EN PROCESO";
            _context.Add(requerimiento);         
            _context.SaveChanges();
            return RedirectToAction("Procesado");
        }

        public IActionResult Responder(Requerimiento req){
            Requerimiento requerimiento= _context.Requerimientos.Where(r => r.ID == req.ID).FirstOrDefault();
            _context.Remove(requerimiento);
            _context.SaveChanges();
            requerimiento.Respuesta= req.Respuesta;
            requerimiento.Fecha_Fin = DateTime.Now;
            requerimiento.Estado="TERMINADO";  
            _context.Add(requerimiento);         
            _context.SaveChanges();
            return RedirectToAction("Terminado");
        }

        public IActionResult Editar(Requerimiento req){
            Requerimiento requerimiento= _context.Requerimientos.Where(r => r.ID == req.ID).FirstOrDefault();
            _context.Remove(requerimiento);
            _context.SaveChanges();
            requerimiento.Tipo_Req= req.Tipo_Req;
            requerimiento.Detalle= req.Detalle; 
            _context.Add(requerimiento);         
            _context.SaveChanges();
            return RedirectToAction("Estudiante");
        }

        public IActionResult Filtrar(Categoria cat){
            var listMostrar= new List<Requerimiento>();
            dynamic modelo = new ExpandoObject();
            for(int i=0; i<listRequerimientos.Count; i++){
                if(listRequerimientos[i].Tipo_Req==cat.ID){
                    listMostrar.Add(listRequerimientos[i]);
                }
            }
            modelo.Mostrar=listMostrar;
            modelo.Categorias=listCategoria;
            modelo.Selected=cat.ID;
            return View("Reportes",modelo);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Listado/Consejero.cshtml
 @model dynamic

 @{
   Categoria cat = new Categoria();
   var listCategoria=@Model.Categorias;
   string id="", rpta="";
 }

  <section id="hero2" class="d-flex justify-content-center align-items-center">
    <div class="container position-relative" data-aos="zoom-in" data-aos-delay="100">

      <h1>@Model.Titulo<br></h1>
      <h1>@Model.Desc</h1>
    </div>
  </section>
  <br>

  <br>

<div class="container col-lg-10"  style="text-align: center;">

  @if(@Model.ReqUser!=null){
    <h2 style="color: black;">Tus requerimientos</h2>
    <table class="table" >
      <thead>
        <tr style="background-color: #910222;">
          <th style="color: white;" scope="col">ID Requerimiento</th>
          <th style="color: white;" scope="col">ID Estudiante</th>
          <th style="color: white;" scope="col">Fecha Inicio</th>
          <th style="color: white;" scope="col">Tipo de Requerimiento</th>
          <th style="color: white;" scope="col">Detalle</th>
          <th style="color: white;" scope="col">Respuesta</th>
        </tr>
      </thead>
      <tbody>
        @foreach (Requerimiento req in @Model.ReqUser)
        {
          id = "Modal"+@req.ID;
          rpta = "Rpta"+@req.ID;

          <tr>
            <th scope="row">@req.ID</th>
            <td>@req.User_ID</td>
            <td>@req.Fecha_Inicio</td>
            @for(int i=0; i<@listCategoria.Count; i++){
              @if(listCategoria[i].ID==@req.Tipo_Req){
                cat=listCategoria[i];
                break;
              }
            }
            <td>@cat.Nombre</td>

            <td>
              <button type="button" class="btn btn-success" data-toggle="modal" data-target="#@id">Ver Detalle</button>
            </td>

            <div class="modal fade" id="@id" tabindex="-1" role="dialog" aria-hidden="true" style="color: black;">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Detalle del requerimiento:</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <textarea type="text"  style="background-color: #910222; color:white;" class="form-control" readonly>@req.Detalle</textarea>
                  </div>
                </div>
              </div>
            </div>

            <td>
              <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#@rpta">Responder</button>
            </td>

            <div class="modal fade" id="@rpta" tabindex="-1" role="dialog" aria-hidden="true" style="color: black;">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">Responder:</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <form asp-action="Responder" asp-controller="Listado">
                      <div class="form-group">
                        <input type="hidden" value="@req.ID" asp-for="@req.ID"/>
                        <textarea type="text"  style="background-color: #910222; color:white;" class="form-control" asp-for="@req.Respuesta"></textarea>
                      </div>
                      <div class="form-group">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>

          </tr>
        }
      </tbody>
    </table>
  <h2 style="color: black;">Otros Requerimientos</h2>
  }
  
  <table class="table" >
    <thead>
      <tr style="background-color: #910222;">
        <th style="color: white;" scope="col">ID Requerimiento</th>
        <th style="color: white;" scope="col">ID Estudiante</th>
        <th style="color: white;" scope="col">Fecha Inicio</th>
        @if(@Model.Titulo!="Requerimientos Pendientes"){
          @if(@Model.Titulo=="Requerimientos Terminados"){
            <th style="color: white;" scope="col">Fecha Finalizacion</th>
          }
          <th style="color: white;" scope="col">ID Consejero</th>
        } 
        <th style="color: white;" scope="col">Tipo de Requerimiento</th>
        <th style="color: white;" scope="col">Detalle</th>
        @if(@Model.Titulo=="Requerimientos Terminados"){
          <th style="color: white;" scope="col">Respuesta</th>
        }else if(@Model.Titulo=="Requerimientos Pendientes"){
          <th style="color: white;" scope="col">Seleccionar</th>
        }
      </tr>
    </thead>
    <tbody>
      @foreach (Requerimiento req in @Model.Mostrar)
      {
        id = "Modal"+@req.ID;
        rpta = "Rpta"+@req.ID;
        <tr>
          <th scope="row">@req.ID</th>
          <td>@req.User_ID</td>
          <td>@req.Fecha_Inicio</td>
          @if(@Model.Titulo=="Requerimientos Terminados"){
            <td>@req.Fecha_Fin</td>
          }
          @if(@Model.Titulo!="Requerimientos Pendientes"){
            <td>@req.Consejero_ID</td>
          }

          @for(int i=0; i<@listCategoria.Count; i++){
            @if(listCategoria[i].ID==@req.Tipo_Req){
              cat=listCategoria[i];
              break;
            }
          }
          <td>@cat.Nombre</td>
          <td>
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#@id">Ver Detalle</button>
          </td>

          <div class="modal fade" id="@id" tabindex="-1" role="dialog" aria-hidden="true" style="color: black;">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Detalle del requerimiento:</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <textarea type="text"  style="background-color: #910222; color:white;" class="form-control" readonly>@req.Detalle</textarea>
                </div>
              </div>
            </div>
          </div>

          @if(@Model.Titulo =="Requerimientos Terminados"){
            <td>
              <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#@rpta">Ver </button>
            </td>

            <div class="modal fade" id="@rpta" tabindex="-1" role="dialog" aria-hidden="true" style="color: black;">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">Respuesta del consejero:</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <textarea type="text"  style="background-color: #910222; color:white;" class="form-control" readonly>@req.Respuesta</textarea>
                  </div>
                </div>
              </div>
            </div>

          }else if(@Model.Titulo=="Requerimientos Pendientes"){
            <td>
              <form asp-action="Seleccionar" asp-controller="Listado"><input type="hidden" asp-for="@req.ID" value="@req.ID"><button type="submit" class="btn btn-warning">Seleccionar</button></form>
            </td>
          }
        </tr>
      }
    </tbody>
  </table>
  </div>

Views/Listado/Estudiante.cshtml
 @model dynamic

 @{
   Categoria cat = new Categoria();
   var listCategoria=@Model.Categorias;
   string id="", rpta="", edit="";
 }
 
 <section id="hero" class="d-flex justify-content-center align-items-center">
    <div class="container position-relative" data-aos="zoom-in" data-aos-delay="100">

      <h1>Ver Estados de Requerimientos<br></h1>
      <h1>  Visualiza el estado de todos tus requerimientos</h1>
    </div>
  </section>
  <br>

<div class="container-fluid" style="text-align: center;">
 <table class="table" >
  <thead>
    <tr style="background-color: #910222;">
      <th style="color: white;" scope="col">ID Requerimiento</th>
      <th style="color: white;" scope="col">Fecha Inicio</th>
      <th style="color: white;" scope="col">Fecha Finalizacion</th>
      <th style="color: white;" scope="col">ID Consejero</th> 
      <th style="color: white;" scope="col">Tipo de Requerimiento</th>
      <th style="color: white;" scope="col">Estado</th>
      <th style="color: white;" scope="col">Detalle</th>
      <th style="color: white;" scope="col">Respuesta</th>
      <th style="color: white;" scope="col">Editar</th>
    </tr>
  </thead>
  <tbody>
      @foreach (Requerimiento req in @Model.Mostrar)
      {
        id = "Modal"+@req.ID;
        <tr>
          <th scope="row">@req.ID</th>
          <td>@req.Fecha_Inicio</td>
          @if(@req.Fecha_Fin!=null){
            <td>@req.Fecha_Fin</td>
          }else{
            <td>----</td>
          }

          @if(@req.Consejero_ID!=null){
            <td>@req.Consejero_ID</td>
          }else{
            <td>----</td>
          } 

          @for(int i=0; i<@listCategoria.Count; i++){
              @if(listCategoria[i].ID==@req.Tipo_Req){
                cat=listCategoria[i];
                break;
              }
            }
          <td>@cat.Nombre</td>
          <td>@req.Estado</td>

          <td>
              <button type="button" class="btn btn-success" data-toggle="modal" data-target="#@id">Ver Detalle</button>
          </td>

          <div class="modal fade" id="@id" tabindex="-1" role="dialog" aria-hidden="true" style="color: black;">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Detalle del requerimiento:</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <textarea type="text"  style="background-color: #910222; color:white;" class="form-control" readonly>@req.Detalle</textarea>
                  </div>
                </div>
              </div>
          </div>

          @if(@req.Respuesta!=null){

            rpta = "Rpta"+@req.ID;

            <td>
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#@rpta">Ver </button>
            </td>

            <div class="modal fade" id="@rpta" tabindex="-1" role="dialog" aria-hidden="true" style="color: black;">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">Respuesta del consejero:</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <textarea type="text"  style="background-color: #910222; color:white;" class="form-control" readonly>@req.Respuesta</textarea>
                    </div>
                  </div>
                </div>
            </div>

          }else{
            <td>
              <button class="btn btn-danger" style="pointer-events: none;" type="button" disabled>Ver </button>
            </td>
          } 

          @if(@req.Estado=="PENDIENTE"){

            edit= "Edit"+@req.ID;

            <td>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#@edit">Editar</button>
            </td>

            <div class="modal fade" id="@edit" tabindex="-1" role="dialog" aria-hidden="true" style="color: black;">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">Editar Requerimiento:</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <form asp-action="Editar" asp-controller="Listado">
                      <div class="form-group">
                        <input type="hidden" value="@req.ID" asp-for="@req.ID"/>
                        <label>Tipo:</label>
                        <select asp-for="@req.Tipo_Req"  class="form-control" style="height: 70px; background-color: #910222; color:white;">
                          @foreach (Categoria cate in listCategoria)
                          {
                            if(@cate.ID==@req.Tipo_Req){
                              <option value="@cate.ID" selected>@cate.Nombre</option>
                            }else{
                              <option value="@cate.ID">@cate.Nombre</option>
                            }
                          }
                        </select>
                      </div>
                      <div class="form-group">
                        <label>Descripcion del Problema:</label>
                        <textarea type="text"  style="background-color: #910222; color:white;" class="form-control" value="@req.Detalle" asp-for="@req.Detalle"></textarea>
                      </div>
                      <div class="form-group">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>

          }else{
            <td>
              <button class="btn btn-primary" style="pointer-events: none;" type="button" disabled>Editar</button>
            </td>
          }

        </tr>
      } 
  </tbody>
</table>
</div>

Views/Listado/Reportes.cshtml
 @model dynamic

 @{
   Categoria cat = new Categoria();
   var listCategoria=@Model.Categorias;
   string id="", rpta="";
 }

  <section id="hero2" class="d-flex justify-content-center align-items-center">
    <div class="container position-relative" data-aos="zoom-in" data-aos-delay="100">

      <h1>Reportes<br></h1>
      <h1>Visualice los requerimientos con filtros de selección</h1>
    </div>
  </section>
  <br>

  <br>

<div class="container">

<form asp-action="Filtrar" asp-controller="Listado">
        <div class="form-group mb-5 center">
        <label class="font-weight-bold center" style="color: black;" >Filtrar por Categoria</label>
        <select class="form-control" style="height: 70px; background-color: #910222; color:white;" asp-for="@cat.ID">
            @foreach (Categoria categoria in @listCategoria)
            {
              @if(@Model.Selected==categoria.ID){
                <option value="@categoria.ID" selected>@categoria.Nombre</option>
              }else{
                <option value="@categoria.ID">@categoria.Nombre</option>
              }
                
            }
        </select>
        <button type="submit" class="get-started-btn center" style="border-radius: 50px;margin:20px;" > Filtrar </button>
        </div>
</form>
  <table class="table searchable sortable center" id='myTable' >
    <thead>
      <tr style="background-color: #910222;">
        <th style="color: white;" scope="col">ID Requerimiento</th>
        <th style="color: white;" scope="col">ID Estudiante</th>
        <th style="color: white;" scope="col">Fecha Inicio</th>
        <th style="color: white;" scope="col">Fecha Finalizacion</th>
        <th style="color: white;" scope="col">ID Consejero</th>
        <th style="color: white;" scope="col">Detalle</th>
        <th style="color: white;" scope="col">Respuesta</th>
      </tr>
    </thead>
    <tbody>
      @foreach (Requerimiento req in @Model.Mostrar)
      {
        
        id = "Modal"+@req.ID;
        rpta = "Rpta"+@req.ID;
        <tr>
          <th scope="row">@req.ID</th>
          <td>@req.User_ID</td>
          <td>@req.Fecha_Inicio</td>

          @if(@req.Estado=="TERMINADO"){
            <td>@req.Fecha_Fin</td>
          }else{
            <td>----</td>
          }

          @if(@req.Estado!="PENDIENTE"){
            <td>@req.Consejero_ID</td>
          }else{
            <td>----</td>
          }

          <td>
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#@id">Ver Detalle</button>
          </td>

          <div class="modal fade" id="@id" tabindex="-1" role="dialog" aria-hidden="true" style="color: black;">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Detalle del requerimiento:</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <textarea type="text"  style="background-color: #910222; color:white;" class="form-control" readonly>@req.Detalle</textarea>
                </div>
              </div>
            </div>
          </div>

          @if(@req.Estado =="TERMINADO"){
            <td>
              <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#@rpta">Ver</button>
            </td>

            <div class="modal fade" id="@rpta" tabindex="-1" role="dialog" aria-hidden="true" style="color: black;">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">Respuesta del consejero:</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <textarea type="text"  style="background-color: #910222; color:white;" class="form-control" readonly>@req.Respuesta</textarea>
                  </div>
                </div>
              </div>
            </div>

          }else{
            <td>
              <button type="button" class="btn btn-danger" disabled>Ver </button>
            </td>
          }
        </tr>
      }
    </tbody>
  </table>
 <script>
function myFunction() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[3];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>
  </div>